name: Run Claude Code Prompt

on:
  schedule:
    - cron: '0 1,6,11,16 * * *' # Run every day at 1, 6, 11, 16 AM UTC
  workflow_dispatch:

jobs:
  claude_code:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
        
      - name: Claude Code Action
        uses: anthropics/claude-code-action@beta
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          mode: agent
          prompt: |
            Current date: ${{ steps.date.outputs.date }}
            Please update the README.md file to include the current date (${{ steps.date.outputs.date }}) in the "Last Updated" section
            
      - uses: quangvo09/claude-code-scheduler@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
