name: Run Claude Code Prompt

on:
  schedule:
    - cron: '0 1,6,11,16 * * *' # Run every day at 1, 6, 11, 16 AM UTC
  workflow_dispatch:

jobs:
  claude_code:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      id-token: write
    steps:
      - name: Claude Code Action
        uses: anthropics/claude-code-action@beta
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          prompt: |
            Continue working on what you were working on previously. If you weren't working on something previously, then come up with a list of tasks to work on based on what is left in the codebase.
